#pragma once

enum class TokenType
{
	LEFT_PAREN, RIGHT_PAREN,
	LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS,
	COLON, SEMICOLON, SLASH, STAR,
	BANG, BANG_EQUAL, EQUAL, 
	LESS, LESS_EQUAL,
	GREATER, GREATER_EQUAL,
	//Types
	FLOAT, INT, STRING, FUNCTION,
	AUTO, ANY, MULTI,
	IDENTIFIER, DEF, 
	//Literals
	STRING_LIT, INT_LIT, FLOAT_LIT,
	TRUE, FALSE, NULL,
	//Keywords
	IF, WHILE, FOR,
	RETURN, ELSE,
	AND, OR,

	ERROR, EOF
};